export const topProducts = [
    { id: 1, name: 'lipstick stick', price: '3 048 ₸', description: 'INFLUENCE BEAUTY influence', image: 'https://images.verishop.com/doll-10-the-multi-tasker-3-in-1-cream-color-stick/7835723727042-3764476317?auto=format&cs=strip&fit=max&w=768&dpr=2' },
    { id: 2, name: 'PRIMER', price: '5 850 ₸', description: 'DARLING* lash cocoon', image: 'https://warpaintformen.com/cdn/shop/products/Primer-01-min_1512x.jpg?v=1700477125' },
    { id: 3, name: 'Powder', price: '7 896 ₸', description: 'ARTDECO perfect teint foundation', image: 'https://warpaintformen.com/cdn/shop/products/Anti-shine-02-min_1512x.jpg?v=1684940668' },
    { id: 4, name: 'Foundation cream', price: '1 459 ₸', description: 'ESSENCE dip eyeliner', image: 'https://images.verishop.com/laura-mercier-real-flawless-foundation/7804033532098-2879903032?auto=format&cs=strip&fit=max&w=768&dpr=2' },
    { id: 5, name: '', price: '10 020 ₸', description: 'KIKO MILANO unlimited blush', image: 'https://images.verishop.com/westman-atelier-super-loaded-tinted-highlight/7804033728706-611752841?auto=format&cs=strip&fit=max&w=768&dpr=2' },
    { id: 6, name: 'Concealer', price: '4 390 ₸', description: 'MAYBELLINE NEW YORK the eraser eye. Консилер для кожи вокруг глаз Maybelline The Eraser Eye быстро спрячет следы усталости, бессонных ночей, стресса и взбодрит чувствительную кожу. Освежит тусклый взгляд, добавит ему сияние. Это средство от Maybelline имеет удобный аппликатор с миниатюрным спонжем. Наносить состав легко и удобно. Формула The Eraser Eye уникальная. В нее включены экзотические компоненты. Среди них целебные ягоды годжи. Они обеспечивают активный уход за веками. Этому консилеру для кожи вокруг глаз непременно следует быть в косметичке каждой девушки.', image: 'https://warpaintformen.com/cdn/shop/products/Concealer-02-min_1512x.jpg?v=1700476964', composition: 'Aqua/Water/Eau, Cyclopentasiloxane, Dimethicone, Isododecane, Glycerin, Peg-9 Polydimethylsiloxyethyl Dimethicone, Butylene Glycol, Dimethicone Crosspolymer, Nylon-12, Disteardimonium Hectorite, Cyclohexasiloxane, Peg-10 Dimethicone, Cetyl Peg/Ppg-10/1 Dimethicone, Phenoxyethanol, Sodium Chloride, Polyglyceryl-4 Isostearate, Caprylyl Glycol, Disodium Stearoyl Glutamate, Ethylhexylglycerin, Methylparaben, Lycium Barbarum Fruit Extract, Chlorphenesin, Ethylparaben, Aluminum Hydroxide, Peg-9, N-Hydroxysuccinimide, Palmitoyl Oligopeptide, Chrysin, Palmitoyl Tetr Apeptide-7. [+/- May Contain/Peut Contenir: Ci 77891/Titanium Dioxide, Ci 77491, Ci 77492, Ci 77499/Iron Oxides]', application: 'Нанести на нужные зоны лица аппликатором, растушевать подушечками пальцев или спонжем. Отлично сочетается со стойкими тональными основами и пудрами серии INFAILLIBLE.' },
   
   
  ];